### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by FedericoFedeFede** [josephdadams/TallyArbiter-GPOListener#1]
Unexpected error: <class 'NameError'>
An error occurred internally.
Traceback (most recent call last):
  File "tallyarbiter-gpolistener.py", line 165, in <module>
    sio.connect('http://' + server + ':' + port)
NameError: name 'server' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tallyarbiter-gpolistener.py", line 179, in <module>
    doBlink(0, 0, 0)
NameError: name 'doBlink' is not defined

**Comment by FedericoFedeFede** [comment]
Fixed with the new update
